import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import dynamic from 'next/dynamic';

//components
import Header from "@/components/Header";

const Cursor = dynamic(() => import('@/components/Cursor'), { ssr: false });

const jetbrainsMono = JetBrains_Mono({ subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"], 
  variable: '--font-jetbrainsMono' });

export const metadata = {
  title: "Vaibhav Panwar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        <Cursor />
        <Header />
        {children}
      </body>
    </html>
  );
}
